const STATUS_FULFILLED = 'STATUS_FULFILLED';
const STATUS_REJECTED = 'STATUS_REJECTED';
const STATUS_PENDING = 'STATUS_PENDING';

export default {
  STATUS_FULFILLED, STATUS_PENDING, STATUS_REJECTED,
};
